name: projeto-redes

services:
  db:
    image: postgres:16.8-alpine3.20
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: redes
    volumes:
      - /var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      frontend:

  app1:
    build: .
    restart: always
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/redes
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      frontend:

  app2:
    build: .
    restart: always
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/redes
    ports:
      - "3001:3000"
    depends_on:
      - db
    networks:
      frontend:

  app3:
    build: .
    restart: always
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/redes
    ports:
      - "3002:3000"
    depends_on:
      - db
    networks:
      frontend:

volumes:
  pgdata:

networks:
  frontend:
    driver: bridge
