global:
  scrape_interval: 15s

scrape_configs:
  - job_name: prometheus
    scrape_interval: 15s
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets:
          - localhost:9090

  - job_name: apps
    metrics_path: /api/metrics
    static_configs:
      - targets:
          - app1:3000
          - app2:3000
          - app3:3000

  - job_name: node_exporter
    static_configs:
      - targets:
          - node_exporter:9100